#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 21 14:34:17 2020

@author: spasagadugula
"""

def decToBin(num):
    
    res = 1

    if num == 1:
        return res
    res = decToBin(num//2)
    return (res*10)+num%2
    
def main():
    print(decToBin(50))

if __name__=="__main__":
    main()
